<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Terms conditions</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="<?= $assets ?>images/favicon.ico"/>
    
    <?php $this->load->view($this->theme . 'frontend_css'); ?>
</head>

<body class="login-page ">
    <div class="fh5co-loader"></div>
    <div id="page">
    	<?php $this->load->view($this->theme . 'frontend_header'); ?>
        <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                </div>
            </div>
        </header>
        <div class="breadcrumb_sec">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <div class="scp-breadcrumb">
                            <ul class="breadcrumb">
                                <li><a href="index.php">Home</a></li>
                                <li class="active">Terms and Conditions</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
         </div>
         <div id="fh5co-contact">

		<div class="container">

			<div class="row">

				<div class="col-sm-12 col-xs-12 terms_conditions">

					<h3>Terms and Conditions</h3>

					<p>These terms and conditions (“user terms”) apply to your visit to and use, of the site whether through a computer or a mobile phone, the service and the application, as well as to all information, recommendations and or services provided to you on or through the site, the service and the application. This document is an electronic record in terms of information technology act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the information technology act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. By clicking on the “i accept” button, you are consenting to be bound by these user terms. Please ensure that you read and understand all these user terms before you use the site. If you do not accept any of the user terms, then please do not use the site or avail any of the services being provided therein. Your agreement to these user terms shall operate as a binding agreement between you and VPick in respect of the use and services of the mobile application and or web site.</p>

					<p>Your acceptance of the User Terms shall be deemed to include your acceptance of the privacy policy available at https://www.vpick.com/privacy-policy.</p>

					<p>By accepting these User Terms, you also allow VPick to send you promotional emails and SMS alerts from time to time.</p>

					<p>It is hereby expressly clarified that these user terms will not apply to a customer taking ‘corporate rides’ i.e., for customers who are availing rides under the direct arrangements between corporate entities and VPick.</p>

					<p><b>1. DEFINITIONS</b></p>

					<p>All of the defined and capitalized terms in these User Terms will have the meaning assigned to them here below:</p>

					<ul>

						<li>“Account” shall mean the account created by the Customer on the Application for availing the Services provided by VPick.</li>

						<li>“Additional Fee” shall mean any toll duty, inter-state taxes, etc. as may not be included in the Fare or not already paid as a part of the Total Ride Fee but payable to any third party / government authorities for undertaking the Ride under Applicable Law</li>

						<li>“Applicable Laws” shall mean and include all applicable statutes, enactments, acts of legislature or parliament, laws, ordinances, rules, by-laws, regulations,notifications, guidelines, policies, directions, directives and orders of any governmental authority, tribunal, or a court of India.</li>

						<li> “Application” shall mean the mobile application “VPick” updated by VPick

from time to time.</li>

						<li>“Convenience Fee”/”Access Fee” shall mean the fee payable by the Customer to VPickfor the Service i.e., for availing the technology services offered by VPick, door to door service, wi-fi access, customer support and cashless payment options. Convenience Fee shall be chargeable on every booking made through the Site. The Convenience Fee shall be exclusive of all applicable taxes on the Convenience Fee, if any.</li>

						<li>“Cancellation Fee” shall mean the Fare and Convenience Fee payable towards cancellation of a Ride by a Customer in terms of Clause 7 of these User Terms and the Cancellation Terms and Conditions available at https://www.vpick.com/cancellation-policy. The Cancellation Fee shall be exclusive of all applicable taxes on the Cancellation Fee, if any.</li>

						<li>“City of Operation” shall mean a city in which the Customers and Third Party Service Providers(TPSP) avail and render the transportation services respectively. For clarity, the services rendered by the TPSPs and availed by the Customers shall be in the same city.</li>

						<li> “Customer/ You” means a person who has an Account on the Application.</li>

						<li>“Driver” shall mean and include such individuals as may be evaluated, appointed and trained by an operator associated with us to provide the transportation services on its behalf and persons who are registered with VPick and own the Vehicles and who have necessary city taxi permits and other applicable transport vehicle permits and licenses to provide transportation services within the City of Operation.</li>

						<li>“E-Wallet” shall mean a pre-paid instrument, which can be used to make payments.</li>

						<li>“Fare” shall mean such amount in Indian Rupees, which is reflected on the Application, as the fare payable for the specific Ride performed by a Driver. The Fare shall be exclusive of all applicable taxes on the Fare, if any. In relation to Auto (a motor cab), the Fare shall be as prescribed by law and/or as stipulated by relevant authorities.</li>

						<li>“Force Majeure Event” shall mean any event arising due to any cause beyond the reasonable control of VPick.</li>

						<li>“VPick” or “us” or “we” or “our” shall mean Eximius Overseas Ventures Pvt. Ltd., a company incorporated under the provisions of the Companies Act, 1956 andhaving its corporate office at 1st Floor, Lodha Capital, Plot No. 426, Sub Plot 1 CTS No. 1074, Gokhale Road, Model Colony, Shivaji Nagar, Pune 411016, Maharashtra India, which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to mean and include all its successors, affiliates and permitted assigns.</li>

						<li>“Registration Data” shall mean and may include the present, valid, true and accurate name, email ID, phone number and such other information as may be required by VPick from the Customer from time to time for registration on the Application.</li>

						<li>“Ride” shall mean the travel in the Vehicle by the Customer facilitated through the Site.</li>

						<li>“Service(s)” means the facilitation of transportation service by VPick through the Application or via a telephone request at the call centre of VPick, or booking on the Site, within the City of Operation, as elaborated in Clause 4.</li>

						<li>“Site” shall mean the Application and the website https://www.vpick.com/ operated by VPick or any other software that enables the use of the Application or such other URL as may be specifically provided by VPick.</li>

						<li>“Substitute Vehicle” shall mean another vehicle arranged for transporting the Customers to his/her destination, in the event of a Vehicle breakdown.</li>

						<li>“Total Ride Fee” shall mean and include the Fare, the Convenience Fee or Access Fee, the Cancellation Fee and Additional Fee and taxes as may be applicable from time to time.</li>

						<li>“T&Cs” and “User Terms” shall mean these Customer terms and conditions.</li>

						<li>“TPSP” shall mean a Driver and/or an operator associated with us offering the service of transporting Customers within the City of Operation as requested by the Customer on the Application.</li>

						<li>“Vehicle” shall mean a motor cab as defined under the Motor Vehicles Act, 1988.</li>

					</ul>

					<p><b>2. ELIGIBILITY</b></p>

					<p>You will be “Eligible” to use the Services only when You fulfil all of the following conditions: (i) You have attained at least 18 (eighteen) years of age. (ii) You are competent to enter into a contract under the Applicable Laws.</p>

					<p>If You reside in a jurisdiction that restricts the use of the Service because of age, or restricts the ability to enter into contracts such as this User Terms due to age, You must abide by such age limits.</p>

					<p><b>3. REGISTRATION AND ACCOUNT</b></p>

					<p>3.1 You understand and acknowledge that You can register on the Site only after complying with the requirements of this Clause 3 and by entering Your Registration Data.<br> 3.2 You shall ensure that the Registration Data provided by You is accurate, complete, current, valid and true and is updated from time to time. We shall bear no liability for false, incomplete, old or incorrect Registration Data provided by You.<br> 3.3 You are solely responsible for maintaining the confidentiality of Your Registration Data and will be liable for all activities and transactions that occur through Your Account, whether initiated by You or any third party. Your Account cannot be transferred, assigned or sold to a third party. We shall not be liable for any loss that You may incur as a result of someone else using Your password or Account, either with or without Your knowledge.<br> 3.4 We reserve the right to suspend or terminate Your Account with immediate effect and for an indefinite period, if We have a reason to believe that the Registration Data or any other data provided by You is incorrect or false, or that the security of Your Account has been compromised in any way, or for any other reason We may find just or equitable. <br>3.5 Except for the Registration Data or any other data submitted by You during the use of any other service offered through Site (“Permitted Information”), VPick does not want You to, and You should not, send any confidential or proprietary information to VPick on the Site or otherwise, unless otherwise is required by Applicable Laws. In accepting these User Terms You agree that any information or materials that You or individuals acting on Your behalf provide to VPick other than the Permitted Information will not be considered confidential or proprietary.<br> 3.6 It is Your responsibility to check to ensure that You download the correct application for Your device. We are not liable if You do not have a compatible mobile device or if You download the wrong version of the Application for Your mobile device. We reserve the right to terminate the Service and the use of the Application should You be using the Service or Application with an incompatible or unauthorized device.<br>3.7 We allow You to open only one Account in association with the Registration Data provided by You. In case of any unauthorized use of Your Account please immediately reach Us at support@vpick.com.<br> 3.8 In case, You are unable to access Your Account, please inform Us at support@vpick.com and make a written request for blocking Your Account. We will not be liable for any unauthorised transactions made through Your Account prior to the expiry of 72 (seventy two) hours after You have made a request in writing for blocking Your Account, and shall not have any liability in case of Force Majeure Event.</p>

					<p><b>4. SERVICES</b></p>

					<p>4.1. The Site permits you to avail the transportation services offered by TPSPs. The Service allows You to send a request through VPick to a Driver on the VPick network. The Driver has sole and complete discretion to accept or reject each request for Service. If the Driver accepts a request, VPick notifies You and provides information regarding the Driver - including Driver name, Vehicle license number, telephone contact details of the Driver and such other details as VPick may determine.</p>

					<p>4.2. VPick shall procure reasonable efforts to bring You into contact with a Driver, subject to the availability of Driver in or around Your location at the moment of Your request for such services.</p>

					<p>4.3. By using the Application or the Service, You further agree that: <br>(i) You will only use the Service or download the Application for Your sole, personal use and will not resell or assign it to a third party; <br>(ii) You will not use an account that is subject to any rights of a person other than

You without appropriate authorization;<br> (iii) You will not use the Service or Site for unlawful purposes;<br> (iv) You will not try to harm the Service, Site or our network in any way

whatsoever; <br>(v) You will provide VPick with such information and documents which VPick may

reasonably request; <br>(vi) You will only use an authorized network to avail the Service;<br> (vii) You are aware that when requesting Services, whether by message, via Site or calling the call center of VPick, standard messaging charges, data charges, voice charges, as applicable, of the Your and Our phone network service providers, will apply; <br>(viii) You will comply with all Applicable Law from Your country of domicile and residence and the country, state and/or city in which You are present while using the Site or Service; and <br>(ix) You are aware of and shall comply with the Information Technology Act,

2000 and the rules, regulations and guidelines notified thereunder.</p>

				<p>4.4. VPick reserves the right to immediately terminate the Service and the use of the Application in the event of non-compliance with any of the above requirements. Further, VPick will store the information provided by You or record your calls for contacting You for all Service related matters. You shall promptly inform VPick on any change in the information provided by You.</p>

				<p>4.5. VPick or an authorised representative of VPick, shall provide information regarding services, discounts and promotions provided by VPick to You by way of an SMS or email to Your registered mobile number/registered email ID. You also have the option to discontinue receiving such information at any point of time. To discontinue receiving such information, You may at any point of time visit the specific link provided in the Site to discontinue the same.</p>

				<p>4.6. VPick will be entitled to process and transfer your information as and when it deems fit and it may store or transfer your information in a server outside india or the country where you are located in order to perform VPick’s obligations under these customer t&c.</p>

				<p>4.7. You agree to grant VPick a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in your information, in any media now known or not currently known, with respect to Your information.<br> YOU AGREE AND PERMIT VPick TO SHARE YOUR INFORMATION AND/OR PERMITTED INFORMATION, WITH THIRD PARTIES.</p>

					

					<p>4.8. You agree and permit VPick to share any information provided by You with third parties in order to facilitate provision of certain value-added services offered by such third parties to You and/or to provide certain value-added services to You by VPick. You hereby expressly consent to receive communications from VPick/ third parties offering value-added services to You through Your registered phone number and/or e-mail id and/or the Site. You agree that You will not hold VPick responsible for any such communications received from third parties, nor will any such communication amount to spam, unsolicited communication or a violation of Your registration on the national do not call registry.</p>

					<p>4.9. VPick will be entitled to enter into any tie-up in terms of joint-venture or otherwise with any other institution engaged in the business of providing services analogous and/or similar to those herein contained. In such case, depending upon the modality and the mechanism as may be devised, You will be provided with the services by VPick jointly and/or severally with the party/ies in joint venture. You hereby give Your irrevocable consent and permission to such a tie-up. In the event of such a tie-up, the terms and conditions herein contained will, mutatis mutandis, become applicable in respect of such tie-up arrangement also.</p>

					<p>4.10. In the event VPick provides You any device as a part of the Services, You shall comply with the following.</p>

					<ul>

						<li>(i) You shall not tamper, pilfer or misuse the VPick Device(s) or allow, induce or assist a third party to indulge in such activity. (ii) You shall not transcribe, distribute, download, store, duplicate and reproduce the content forming part of the VPick Device(s) (“Content”), in whole or in part, through any medium including, but not limited to, tape, disc, hard disk, computer system, or other electronic recording or transmission device.</li>

						<li>(iii) You shall not (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party, in any way, the VPickDevice(s) and/or any Content; (ii) modify or make derivative works from the Content; (iii) create Internet “links” to the Content or “frame” or “mirror” any Content on any other server or wireless or internet-based device; (iv) reverse engineer or access the VPick Device(s) and/or Content in order to (a) design or build a competitive product or service, (b) design or build a product using similar ideas, features, functions or graphics of the VPick Device(s) and/or Content, or (c) copy any ideas, features, functions or graphics of the VPick Device(s) and/or Content, or (v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the VPick Device and/or Content (iv) You shall not use the VPick Device(s) for any illegal or unlawful purposes including but not limited to playing / watching pornographic content on the VPick Device and shall use the VPick Device(s) solely for purposes determined by VPick and strictly in accordance with these User Terms. You shall solely be responsible and liable for any violations of law committed by You and misuse of the VPick Device(s), if any, with the VPick Device(s). (v) You shall ensure that the VPick Device(s) is maintained in Your possession in a proper manner. VPick may, at its sole discretion, charge such amounts from You as may be determined by VPick for use of the VPick Device(s) by You. (vi) In the event the VPick Device(s) is not functioning properly or if there is any technical or safety issue in relation to the VPick Device(s), You shall immediately inform the Driver about any such issue. (vii) You shall use the VPick Device(s) with due care and caution and not do anything or permit anything to be done that may cause damage to the VPick Device(s). If the VPick Device(s) is damaged and is not repairable due to any act of You, You shall pay amounts to VPick, as may be determined by VPick. If You fail or are unable to pay the amounts determined by VPick, VPick shall be entitled to suspend / terminate Your Account with VPick without prejudice to VPick’s rights under these User Terms and under Applicable Laws.</li>

					</ul>

					<p>4.11. In the event of breakdown of the Vehicle, which is beyond repair, before completion of the Ride, VPick on a best effort basis and at its sole discretion may arrange for a Substitute Vehicle for completion of Your Ride to Your destination. However, the arrangement of Substitute Vehicle shall be subject to its availability.</p>

					<p>4.12. You acknowledge and agree that Substitute Vehicle may not be necessarily of the same type as the original Vehicle booked by You from the Site.</p>

					<p>4.13. VPick bears no responsibility and liability for delays and losses suffered by You or caused to You as a consequence of the breakdown of the Vehicle or the Substitute Vehicle.</p>

					<p><b>5. CONFIRMATION OF BOOKING</b></p>

					<p>5.1. VPick shall, upon receiving the booking request from You in the manner set out above, proceed to confirm or decline the booking based on the availability of Vehicles at the pickup time, which shall be informed to You vide an SMS or email. In the event the booking is confirmed, You shall check the booking details including but not limited to pick up time and pick up place, and if there is incorrect detail, the same needs to be informed to us immediately by calling our call centre.</p>

					<p>5.2. You shall bear the consequences and damages for any delay that may be caused to You due to Your failure to check the confirmation SMS or email or failure to inform VPick of the incorrect details immediately.</p>

					<p>5.3. Certain selective customers will be eligible to avail the Service under a ‘Guest Booking’ feature, provided by VPick. Such customers will also be bound by the terms and conditions set out herein.</p>

					<p><b>6. PAYMENT</b></p>

					<p>6.1. TPSP shall charge Fare to You for the Ride offered to You by the TPSP.</p>

					<p>6.2. You shall be required to pay such Additional Fee, which will form part of the receipt of the Total Ride Fee.</p>

					<p>6.3. You shall be required to pay such Cancellation Fee in terms of Clause 7,</p>

					<p>6.4. In addition to the Total Ride Fee, You may be required to pay such other charges incurred by you during the Ride in cash i.e. Additional Fee, which are not included in the receipt of the Total Ride Fee.</p>

					<p>6.5. The Total Ride Fee will be collected by the Driver from You at the end of the Ride, as set out in Clause 6.8 below.</p>

					<p>6.6. VPickshall provide a receipt of the Total Ride Fee payable by You at the end of the Ride, however, separate invoices raised by the TPSPs for the Fare and Additional Fee, and the Convenience Fee or Access Fee raised by VPickshall be provided to You on request. You may raise a request for a copy of the invoices from our Support page.</p>

					<p>6.7. All applicable taxes in respect of the Fare, Convenience Fee, Additional Fee, Cancellation Fee shall be borne and payable by You to the TPSPs or VPick, as the case may be.</p>

					<p>6.8. You shall choose to pay for the Service Fee by either of the following three methods:</p>

					<ul>

						<li>Cash payment: Cash payment towards the Total Ride Fee after the completion of Ride can be made to the Driver. </li>

						<li>E-Wallet payment: VPickoffers You the facility of making an online payment through an E-Wallet powered by a third party payment processor (“Payment Processor”). E-Wallet money will not be applicable on bookings made through the phone or while the user is not logged into his/her Account on the Site. The processing of payments, in connection with Your use of the E-Wallet will be subject to the terms, conditions, and privacy policies of the Payment Processor that VPick engages for the purpose. VPick will not be responsible for any errors by the Payment Processor in any manner. Further, even in cases of E- Wallet payments, all Additional Fee (defined below) shall have to be paid by You in cash, to the authority or person concerned or if already paid by the Driver, to the Driver. When You choose to make an E-Wallet payment, VPick shall collect the Fare on behalf of the TPSP who will be responsible for providing the transportation services.</li>

						<li>Credit Card/ Debit Card/ Net Banking Payment: Total Ride Fee shall be effected using the services of an entity providing payment gateway/processor services (“PG”), authorized by VPick. Such PG may either be VPick or any of its affiliates or partners or unrelated third parties. You agree and undertake to share relevant payment details including credit/debit card details (Card Details) with the PG for the successful completion of payment towards Total Ride Fee to VPick and authorize the PG to complete such transactions. In this respect, it is clarified that all PGs whose services are utilized for the purposes of the Site and/or Application and/or Services shall be PCI-DSS (Payment Card Industry – Data Security Standard) compliant. Your authorization permits the PG to debit or credit the bank account associated with Your payment details. Your authorization further permits the PG to use Your Card Details for the processing of transactions initiated by You at any of VPick’s affiliates. Your authorization will remain in effect as long as You maintain an Account with Us. In the event You delete Your Card Details with the PG or if You delete Your Account, the PG will not process any further transactions initiated by You at the Site or Application and at the sites of any of VPick’s affiliates. Your authorization under this clause is subject to any other terms and conditions of the PG.</li>

					</ul>

					<p>6.10. Any payment related issue, except when such issue is due to an error or fault in the Site, shall be resolved between You and the Payment Processor. VPick shall not be responsible for any unauthorized use of Your E-Wallet during or after availing the Services on the Site.</p>

					<p>6.11. If You are not satisfied with the service provided by VPick or any of it’s associated TPSPs, you are to raise a complaint within 24 hours of the service in question in writing at the registered office 1st Floor Lodha Capital, Model Colony, Shivajinagar, Pune 411016, Mahashtra, India or via email at support@vpick.com. VPick ensures resolution of any and all complaints within 30 days of receiving said complaint. If after the investigation VPick finds itself or it’s TPSP at fault, VPick assures 100% money back guarantee after 7 business days of resolution.</p>

					<p><b>7. CANCELLATION POLICY</b></p>

					<p>7.1. You agree and acknowledge that You may cancel Your request for a Vehicle from a Driver at any point of time subject to a Cancellation Fee as explained below:</p>

					<p>In Micro/Mini/Prime/Sedan/SUV/Luxury/Rental categories, Cancellation Fee will be charged</p>

					<ul>

						<li>If you cancel after 5 minutes after the cab is allotted or</li>

						<li>If a driver cancels after waiting at Your location for more than 10 minutes</li>

						<li>Notwithstanding the foregoing, if the Driver is delayed by more than five (5) minutes to pick You, You will not be charged any Cancellation Fee.</li>

					</ul>

					<p>7.2. You shall be notified of the applicable Cancellation Fee in advance whenever You attempt to cancel a booking/service request. The notification shall be on the Application and/or the Site.</p>

					<p>7.3. VPick shall provide a receipt of the Cancellation Fee, if any, payable by You for every cancellation in terms of the table above for such cancellations, however, separate invoices raised by the TPSPs for the Cancellation Fee, and VPick for the Convenience Fee on cancellations shall be provided to You on request. You may raise a request for a copy of the invoices from the Support page.</p>

					<p>7.4. The Cancellation Fee shall be payable by You at the completion of Your subsequent Ride.</p>

					<p>7.5. The mode of payment of the Cancellation Fee shall be in terms of Clause 7 of these User Terms.</p>

					<p>7.6. This Clause 7 shall not apply to corporate rides availed pursuant to the terms and conditions.</p>

					<p><b>8. USER VIOLATION OF USER TERMS</b></p>

					<p>8.1. You shall not smoke and drink in the Vehicles or misbehave with the Driver or distract the Driver or act in violation of Applicable Law. In the event You are found to be involved in the activities set out above, You shall be liable to pay a fine to us and we shall also have the right to terminate the Ride. In the event You fail to pay fine after the completion of the Ride, we may at our discretion, take such steps as may be available to us under Applicable Law. You shall also be blacklisted as a result of non-payment of the fine or misbehaving as the case may be, and in such event, Your Account may be terminated by VPick.</p>

					<p><b>9. CUSTOMER RELATIONSHIP MANAGEMENT </b></p>

					<p>9.1. All issues, opinions, suggestions, questions and feedback while availing our Services shall be communicated to us through email address mentioned in Clause 22.2. In case of a Ride booked on our Application, You shall be required to rate the Ride after its termination. You agree to be fair, accurate and non-disparaging while leaving comment, feedbacks, testimonials or reviews on or about the Rides or Services.</p>

					<p>9.2. Reporting of any issue needs to be within 7 (seven) days of the happening of the issue, failing which, such issue will not be addressed.</p>

					<p>9.3. Any issue reported on channels other than the above may be addressed by VPick only on a best-effort basis. VPick takes no liability for inability to get back on other channels.</p>

					<p>9.4. VPick shall endeavour to respond to Your issues within 2 (two) working days of Your reporting the same and endeavour to resolve it at the earliest possible. It is hereby clarified that issues are resolved on severity basis, and certain may be resolved earlier than the other. However, VPick shall not be liable for any damages or losses in the event You are not satisfied with any such resolution.</p>

					<p><b>10. EMERGENCY SERVICES TO CUSTOMER</b></p>

					<p>10.1 By accepting these User Terms and on pressing the SOS button on the VPick App, You consent to VPick using its best endeavours to provide You with assistance during a safety incident, emergencies or distress, as per VPick’s internal policies on emergency response. VPick may undertake remedial action(s), including, but not limited to the following:</p>

					<ul>

						<li>When you press the SOS button and report a safety incident, the VPick representative may escalate the incident internally or liaise with any third party security service providers to assist You and/or deploy response teams to Your location.</li>

						<li>VPick may inform any government authorities, such as the concerned police station, about the incident and seek their assistance; VPick may also provide such authority(ies) with your personal information including but not limited to your exact GPS location, your registered email ID and mobile number to enable them to take appropriate steps to assist You. </li>

						<li>VPick may engage third party security providers to assist You and VPick in addressing the incident. For this purpose, VPick may share your personal information, including but not limited to, your exact GPS location, your registered email ID and mobile number with third parties such as a security services provider, to enable them to take appropriate steps to assist You and solely to resolve the incident. 10.1.4 Further to the above, You may receive telephone calls from an VPick representative and/or the relevant response team at the time of pressing the SOS button and in the duration that the incident is being resolved, and the same shall not be construed as breach of TRAI guidelines, in as much as these would be made for Your security and safety purposes.</li>

					</ul>

					<p>10.2 Under this clause, You give Your express consent to permit VPick to undertake the above along with any ancillary actions that may be required to facilitate an effective emergency response.</p>

					<p>10.3 VPick will not be liable for any deficiency of service, provided to You under this clause on a best efforts basis, and this clause does not, in any manner, restrain You from seeking any other form of assistance from any other party.</p>

					<p><b>11. FORCE MAJEURE</b></p>

					<p>11.1 We shall not be liable for any failure to perform any obligations under this User Terms, if the performance is prevented, hindered or delayed by a Force Majeure Event and in such case our obligations under this User Terms shall be suspended for so long as the Force Majeure Event continues.</p>

					<p><b>12. INDEMNIFICATION</b></p>

					<p>12.1 By accepting these User Terms and using the Service, You agree that You shall defend, indemnify and hold VPick, its affiliates, their licensors, and each of its officers, directors, other users, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with: (a) Your violation or breach of any term of these User Terms or any Applicable Law or regulation, whether or not referenced herein; (b) Your violation of any rights of any third party, including the TPSPs \or (c) Your use or misuse of the Application or Service.</p>

					<p><b>13. LIABILITY</b></p>

					<p>13.1. The information, recommendations and/or Services provided to You on or through the Site, the Application and VPick call center are for general information purposes only and does not constitute advice. VPick will reasonably keep the Site and its contents correct and up to date but does not guarantee that (the contents of) the Site is free of errors, defects, malware and viruses or that the Site is correct, up to date and accurate.</p>

					<p>13.2. VPick shall not be liable for You missing trains/flights/events or delays etc. as the Service is dependent on many factors not in VPick’s control. You must book Your Ride after taking into account the check-in time, traffic and weather conditions, political rallies, natural calamities, traffic barricades, car breakdowns and other un-expected delays.</p>

					<p>13.3. In the event, there is a delay by the Vehicle in reaching the pickup location beyond 30 (thirty) minutes of the pickup time, VPick shall only endeavour to get You in touch with the Driver assigned for Your Ride.</p>

					<p>13.4. VPick shall not be liable for any damages resulting from the use of or inability to use the Site, including damages caused by wrong usage of the Site, error in call centre number, network issues, malware, viruses or any incorrectness or incompleteness of the Information or the or Application.</p>

					<p>13.5. You shall take full responsibility of Your items and luggage. In case of lost items inside the Vehicle during the journey, VPick will try to locate the items on a “best-effort” basis but is not responsible for the same in case of loss or damage to the same. If You leave any goods in the Vehicle or have any complaint in respect of the Services or the use of the Vehicle, You have to inform VPick of the same in writing within 24 (twenty four) hours of using the Vehicle or the Services of VPick. In the event it is found, You shall be informed about the VPick office from where You can collect it after 3 (three) working days from the date You were informed. VPick however shall not be responsible for delivering the same back to You. If requested, VPick may deliver the misplaced item/s back to You after 3 (three) working days from the date You were informed, subject to the place of delivery being twenty (20) kms from the VPick office. VPick shall charge You a flat fee of Rs 500 for such delivery.</p>

					<p>13.6. VPick does not assure a complete sustainability of its Service and shall not be held responsible or liable for the same, in any manner.</p>

					<p>13.7. VPick shall not be responsible for any loss of communication / information of status update and benefits under the program. All this information will be sent on mobile number and/or email ID registered with VPick. VPick will not be responsible for appropriateness of mobile or email or any other communication medium. You shall be responsible for immediately reporting the errors, if any, occurred in the information sent to You regarding booking confirmation.</p>

					<p>13.8. In no event shall VPick be liable for any direct, indirect, punitive, incidental, special or consequential damages or for any damages whatsoever, whether based on contract, tort, negligence, strict liability or otherwise, even if VPickhas been advised of the possibility thereof.</p>

					<p>13.9. In addition, and without limiting the foregoing, to the fullest extent permitted by applicable law, in no event will VPick’s aggregate liability arising out of or in connection with these user terms or the services rendered hereunder, whether in contract, tort (including negligence, product liability, or other theory), warranty, or otherwise, exceed the amount of Rs. 1000/- (Rupees One Thousand only).</p>

					<p>13.10. If Applicable Law does not permit the exclusion of certain warranties or the

limitation or exclusion of liability, the scope and duration of such warranty exclusions and the extent of the liability of VPick shall be the minimum permitted under Applicable Law.</p>

		<p><b>14. APPLICATION LICENSE</b></p>

		<p>14.1. Subject to Your compliance with these User Terms, VPick grants You a limited, revocable, non-exclusive, non-transferable and non-sub-licensable license to download and install a copy of the Application on a single mobile device that You own or control and to run such copy of the Application solely for Your own personal use and to use the Site.</p>

		<p>14.2. You shall not <br>(i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service or Site in any way; <br>(ii) modify or make derivative works based upon the Service or Application;<br> (iii) create Internet “links” to the Service or “frame” or “mirror” any Site on any other server or wireless or Internet-based device;<br> (iv) reverse engineer or access the Site in order to (a) design or build a competitive product or service, (b) design or build a product using similar ideas, features, functions or graphics of the Service or Site, or (c) copy, reproduce, record, or make available to the public any ideas, features, functions or graphics of the Service or Site, or (v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Service or Site.</p>

		<p>14.3. You shall not: <br>(i) send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; <br>(ii) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including material harmful to children or violation of third party privacy rights; <br>(iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs;<br> (iv) interfere with or disrupt the integrity or performance of the Site, the Application or Service or the data contained therein; or<br> (v) attempt to gain unauthorized access to the Site, the Application or Service or its related systems or networks.</p>

		<p>14.4. VPick will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. VPick may involve and cooperate with law enforcement authorities in prosecuting users who violate these User Terms. You acknowledge that VPick has no obligation to monitor Your access to or use of the Site, Service or Posted Content, but has the right to do so for the purpose of operating the Site and Service, to ensure Your compliance with these User Terms, or to comply with Applicable Law or the order or requirement of a court, administrative agency or other Governmental body. VPick reserves the right, at any time and without prior notice, to remove or disable access to any content that VPick, at its sole discretion, considers to be in violation of these User Terms or otherwise harmful to the Site, the Service or Application.</p>

		<p><b>15. CONTENT POSTED BY CUSTOMERS</b></p>

		<p>15.1. VPick may accept posting of any notes, messages, e-mails, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information given by you on the Site (“Posted Content”) by You. You represent that You have obtained all permissions and consents required to post the Posted Content and such Posted Content complies with all requirements of the Posted Content. VPick shall not in any manner be responsible for or endorse the Posted Content.</p>

		<p>15.2. You agree that when posting Posted Content, You will not:</p>

		<ul>

			<li>Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, blasphemous, pornographic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful material or information.</li>

			<li>Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy or publicity) unless You own or control the rights thereto or have received all necessary consents. </li>

			<li>Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another’s computer. (iv) Advertise or offer to sell or buy any goods or services for any business purpose, unless the Site specifically allows such messages.</li>

			<li>Conduct or forward surveys, contests, pyramid schemes or chain letters. </li>

			<li>Download any file posted by another user that You know, or reasonably should know, cannot be legally distributed in such manner.</li>

			<li>Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</li>

			<li>Deceive or mislead the addressee about the origin of a message or communicate any information which is grossly offensive or menacing in nature. </li>

			<li>) Restrict or inhibit any other user from using and enjoying the Site.</li>

			<li>ViVPickte any code of conduct or other guidelines which may be applicable for

any particular Posted Content.</li>

			<li>Harvest or otherwise collect information about others, including e-mail addresses, without their consent. </li>

			<li>Threaten the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation. </li>

			<li>Violate any Applicable Laws or regulations including the Information Technology Act, 2000 and the rules, regulations and guidelines notified thereunder.</li>

			

		</ul>

		<p><b>16. INTELLECTUAL PROPERTY OWNERSHIP</b></p>

		<p>16.1. VPick alone (and its licensors, where applicable) shall own all right, title and

interest, including all related intellectual property rights, in and to

</p>

		<ul>

			<li>The Site, Application, product, Service and any suggestions, ideas, enhancement requests, feedback, recommendations or any other offering; </li>

			<li>text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code; or </li>

			<li>other information provided by You or any other party relating to the Site, Application or the Service. Third party trademarks may appear on this Site/ Application and all rights therein are reserved to the registered owners of those trademarks. For use of any third party's intellectual property, You need to get permission directly from the owner of the intellectual property for any use.</li>

		</ul>

			<p>16.2. These User Terms do not constitute a sale and do not convey to You any rights of ownership in or related to the Site, the Application or the Service, or any intellectual property rights owned by VPick. You shall be solely responsible for any violations of any laws and for any infringements of any intellectual property rights caused by use of the Services or the Site/ Application.</p>

			<p>16.3. You may use information on the Site purposely made available by VPick for

downloading from the Site, provided that You:

</p>

			<ul>

				<li>do not remove any proprietary notice language in all copies of such documents and make no modifications to the information; </li>

				<li>use such information only for Your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media; or </li>

				<li>do not make any additional representations or warranties relating to such information.</li>

				<li></li>

			</ul>

			<p><b>17. LINKS</b></p>

			<p>17.1. If permitted by VPick, You may establish a hypertext link to the Site, provided that the link does not state or imply any sponsorship or endorsement of Your site by Us. You must not use on Your site or in any other manner any VPick trademarks or service marks or any Content belonging to VPick and appearing on the Site, including any logos or characters, without our express written consent. You must not frame or otherwise incorporate into another third party website or present in conjunction with or juxtaposed against such a website any of the content or other materials on the Site without our prior written consent.</p>

			<p><b>18. TERM AND TERMINATION OF LICENSE AGREEMENT</b></p>

			<p>18.1. Unless terminated in accordance with this Clause 17, the agreement between VPick and You is perpetual in nature upon downloading the Application and for each Ride booked through the Site.</p>

			<p>18.2. You are entitled to terminate the agreement at all times by deletion of Your Account, thus disabling the use by You of the Site. You can close Your Account at any time by following the instructions on the Site.</p>

			<p>18.3. VPick is entitled to terminate the agreement at all times and with immediate effect (by disabling Your use of the Site and the Service) if You: (a) violate or breach any term of these User Terms, or (b) in the opinion of VPick, misuse the Application or the Service. VPick is not obliged to give notice of the termination of the agreement in advance. After termination VPick will give notice thereof in accordance with these User Terms.</p>

			<p>18.4. Termination of this agreement will not prejudice accrued rights of either VPick or You.</p>

			<p>18.5. Clauses 11 (Indemnification), 12 (Liability), 13 (Application License), 14 (Contents posted on Site/ Application), 15 (Intellectual Property Ownership), 17 (Term and Termination), 22 (Notice) and 24 (Applicable Law and Dispute Resolution) and such other provisions which are intended to survive the termination, shall survive the expiry/termination of these User Terms in accordance with their terms.</p>

			<p><b>19. INVALIDITY OF ONE OR MORE PROVISIONS</b></p>

			<p>19.1. The invalidity of any term of these User Terms shall not affect the validity of the other provisions of these User Terms. If and to the extent that any provision of these User Terms is invalid, or is unacceptable in the given circumstances, a provision shall apply between the parties instead that is acceptable considering all the circumstances, taking into account the content and the purpose of these User Terms.</p>

			<p><b>20. CONFLICT</b></p>

			<p>In the event of any contradiction or inconsistency between this User Terms and any other agreement executed between You and VPick, the terms of the User Terms shall prevail unless the exception has been expressly agreed to in writing by making reference to the relevant Clause sought to be modified under this User Terms.</p>

			<p><b>21. DISCLAIMER</b></p>

			<p>21.1. You agree that VPick is merely an electronic platform to facilitate aggregation of Vehicles and does not in any manner provide transportation services. VPick does not endorse, advertise, advise or recommend You to avail the Services of any Driver. VPick also does not guarantee or provide assurance in respect of the behaviour, actions or data of the users posted on the Site.</p>

			<p>21.2. We do not authorize anyone to make a warranty on Our behalf and You shall not rely on any statement of warranty as a warranty by Us.</p>

			<p>21.3. VPick and their representatives, officers, employees, agents and contractors shall not be liable for any loss, damage, claim, expense, cost (including legal costs) or liability arising directly or indirectly from Your use or non-use of the Service or the Site, or Your reliance upon the Service or the information contained upon the Site (whether arising from VPick or any other person's negligence or otherwise).</p>

			<p>21.4. This Site, Application and all content on the Site and the Application are provided on an “as is” basis without warranties of any kind, either express or implied, including without limitation warranties of title or implied warranties of merchantability or fitness for a particular purpose. You acknowledge, by Your access of the Site and/or Application, that Your access of the Site and/or Application and availing of Services is at Your sole risk, that You assume full responsibility for Your access and use of the Site and/or Application, and that VPick shall not be liable for any damages of any kind related to Your access and use of this Site and/or Application.</p>

			<p>21.5. All images, audio, video and text in the Site and/or Application are only for illustrative purposes. None of the models, actors or products in the images, if any is endorsing the Services in any manner. Any resemblance of any matter to anybody or anything is purely unintentional and/or coincidental.</p>

			<p>21.6. VPick is not engaged in the insurance business and does not provide any insurance services. VPick has facilitated provision of insurance services for the benefit of Customers, under group travel insurance policies availed from insurance companies, whereby VPick is acting as the group manager of the policy. VPick does not guarantee or make any promise in relation to the insurance policy/ insurance company, including but not limited to any benefits from use of the insurance services provided by the insurance companies, such as coverage, claims and settlements. Any claim or servicing of insurance policies, raised through the Application, remains a matter between the Customer and the insurance company, and VPick shall not be responsible for the actions of the insurance company or the Customer. It is to be noted that the insurance policy number, claim certificate, invoice for the insurance premium/ fee collected from the Customer is not be issued by VPick, but will be issued by the respective insurance company. Any issues in receiving tax invoices or issues faced in claiming the insurance are not the responsibility of VPick. VPick disclaims all and all liability in relation to the services of the insurance company. Please reach out to the insurance company in case of any questions/ issues.</p>

			<p><b>22. MODIFICATION OF THE SERVICE AND USER TERMS</b></p>

			<p>22.1. VPick reserves the right, at its sole discretion, to modify or replace, in part or full, any of these User Terms, or change, suspend, block, discontinue or restrict your use to all or any feature of the Service or Application at any time.</p>

			<p>22.2. VPick shall not be required to notify You of any changes made to these User Terms. The revised User Terms shall be made available on the Site. You are requested to regularly visit the Site to view the most current User Terms. You can determine when VPick last modified the User Terms by referring to the “Last Updated” legend above. It shall be Your responsibility to check these User Terms periodically for changes. VPick may require You to provide Your consent to the updated User Terms in a specified manner prior to any further use of the Site and the Services. If no such separate consent is sought, Your continued use of the Site, following the changes to the User Terms, will constitute Your acceptance of those changes. Your use of the Site and the Services is subject to the most current version of the User Terms made available on the Site at the time of such use.</p>

			<p><b>23. NOTICE</b></p>

			<p>23.1. VPick may give notice by means of a general notice on the Service or Application, or by electronic mail to Your email address or a message on Your registered mobile number, or by written communication sent by regular mail to Your address on record in VPick’s account information.</p>

			<p>23.2. You may contact VPick by electronic mail at Our email address legalnotice@vpick.com or by written communication sent by regular mail to Our address at 1st Floor, Lodha Capital, Model Colony, Shivaji Nagar, Pune 411016, Maharashtra, India.</p>

			<p><b>24. ASSIGNMENT</b></p>

			<p>24.1. You shall not assign Your rights under these User Terms without prior written approval of VPick. VPick can assign its rights under the User Terms to any affiliate.</p>

			<p><b>25. APPLICABLE LAW AND DISPUTE RESOLUTION</b></p>

			<p>These User Terms are subject to the laws of India. Any dispute, claim or controversy arising out of or relating to these User Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Site, the Service or the Application (collectively, “Disputes”) the parties shall attempt to settle the same amicably, through negotiation and consultation at such offices of VPick as VPick may designate. In the event the dispute is not resolved internally between after at least 30 (thirty) days of negotiation, in good faith, the same shall be subject to binding and final arbitration in accordance with the Arbitration and Conciliation Act, 1996 as amended from time to time or in case the Arbitration and Conciliation Act, 1996 is no longer in force, as per any law relating to arbitration in force at the time of such reference. The reference shall be made to a sole arbitrator mutually appointed by VPick and You. The place of the arbitration shall be Pune, Maharashtra, unless otherwise mutually agreed by VPick and You in writing. Subject to the above, any Dispute will be subject to the exclusive jurisdiction of courts in Pune, India.</p>

			

				</div>

			</div>

		</div>

	</div>
         <?php $this->load->view($this->theme . 'frontend_footer'); ?>
         
    </div>
    <?php $this->load->view($this->theme . 'frontend_js'); ?>
<!--<script src="<?= $assets ?>js/jquery.js"></script>
<script src="<?= $assets ?>js/bootstrap.min.js"></script>-->
</body>
</html>
